# -*- coding: utf-8 -*-
"""Number_Programs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O1iyWHSomBIL14QqeSZHxkq0nGAMXlrk
"""

#Tech Number or not
num = int(input("Enter a number: "))
num_str = str(num)
n = len(num_str)

if n % 2 == 0:  # Check even digits
    first_half = int(num_str[:n//2])
    second_half = int(num_str[n//2:])
    if (first_half + second_half) ** 2 == num:
        print(num, "is a Tech Number")
    else:
        print(num, "is NOT a Tech Number")
else:
    print(num, "is NOT a Tech Number")

#Peterson Number
num = int(input("Enter a number: "))
temp = num
sum_fact = 0

while temp > 0:
    digit = temp % 10
    fact = 1
    for i in range(1, digit + 1):
        fact *= i
    sum_fact += fact
    temp //= 10

if sum_fact == num:
    print(num, "is a Peterson Number")
else:
    print(num, "is NOT a Peterson Number")

#Sunny Number
import math

num = int(input("Enter a number: "))

# To Check if num + 1 is a perfect square
if math.isqrt(num + 1) ** 2 == num + 1:
    print(num, "is a Sunny Number")
else:
    print(num, "is NOT a Sunny Number")

#Spy Number
num = int(input("Enter a number: "))
temp = num
sum_digits = 0
prod_digits = 1

while temp > 0:
    digit = temp % 10
    sum_digits += digit
    prod_digits *= digit
    temp //= 10

if sum_digits == prod_digits:
    print(num, "is a Spy Number")
else:
    print(num, "is NOT a Spy Number")

#Neon Number
num = int(input("Enter a number: "))
square = num * num
sum_digits = 0

while square > 0:
    digit = square % 10
    sum_digits += digit
    square //= 10

if sum_digits == num:
    print(num, "is a Neon Number")
else:
    print(num, "is NOT a Neon Number")

#Keith Number
num = int(input("Enter a number: "))
num_str = str(num)
digits = [int(d) for d in num_str]
n = len(digits)

temp = sum(digits)

# To Generate sequence until temp >= num
while temp < num:
    digits.append(temp)
    temp = sum(digits[-n:])

if temp == num:
    print(num, "is a Keith Number")
else:
    print(num, "is NOT a Keith Number")